[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
savant_core = { git = "https://github.com/insight-platform/savant-rs", tag = "0.2.18" }
anyhow = "1"
uuid = { version = "1", features = ["v7"] }
